# Generated by Django 3.2.25 on 2025-06-26 06:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'base_message_readers',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='message',
            name='readers',
            field=models.ManyToManyField(blank=True, related_name='read_messages', through='base.MessageReaders', to=settings.AUTH_USER_MODEL),
        ),
    ]
